### ISSUE TITLE
huey_monitor generates error when launching Testing

### ISSUE THREAD

**Issue by Skrattoune** [boxine/django-huey-monitor#30]
Hi,

I've been implementing django-huey with django-huey-monitor.
It starts to do more or less what I want (please look also into the discussion thread https://github.com/boxine/django-huey-monitor/discussions/28).

... until I started to launch some testing on a totally unrelated part of my application.

And there, surprise, I have an avalanche of errors linked to django-huey-monitor during the setup of the Testing environement (cf Traceback below).

There is not much about huey_monitor on the net or in term of documentation, so I'll greatly appreciate I you could help me out.

```
Error occurred sending signal "executing"
Traceback (most recent call last):
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: huey_monitor_taskmodel

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\...\venv\lib\site-packages\huey\api.py", line 274, in _emit
    self._signal.send(signal, task, *args, **kwargs)
  File "C:\Users\...\venv\lib\site-packages\huey\signals.py", line 41, in send
    receiver(signal, task, *args, **kwargs)
  File "C:\Users\...\venv\lib\site-packages\huey_monitor\tasks.py", line 49, in store_signals
    defaults={'name': task.name}
  File "C:\Users\...\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "C:\Users\...\venv\lib\site-packages\nplusone\core\signals.py", line 23, in wrapped
    ret = func(*args, **kwargs)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\Users\...\venv\lib\site-packages\nplusone\ext\django\patch.py", line 295, in fetch_all
    original_fetch_all(self)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\...\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1169, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\...\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: huey_monitor_taskmodel
Unhandled exception in task 20046722-1606-4d32-80a2-3f88ed08d4fe.
Traceback (most recent call last):
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: huey_monitor_taskmodel

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\...\venv\lib\site-packages\huey\api.py", line 367, in _execute
    task_value = task.execute()
  File "C:\Users\...\venv\lib\site-packages\huey\api.py", line 740, in execute
    return func(*args, **kwargs)
  File "C:\Users\...\venv\lib\site-packages\huey\contrib\djhuey\__init__.py", line 133, in inner
    return fn(*args, **kwargs)
  File "C:\Users\...\goodies\decorators\debug.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\...\puzzles\tasks\puzzles.py", line 49, in recalculate_pzl_medians
    unit='puzzles',
  File "C:\Users\...\venv\lib\site-packages\huey_monitor\tqdm.py", line 47, in __init__
    unit_divisor=self.unit_divisor,
  File "C:\Users\...\venv\lib\site-packages\django\db\models\query.py", line 783, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1535, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1169, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\...\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: huey_monitor_taskmodel
Error occurred sending signal "error"
Traceback (most recent call last):
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: huey_monitor_taskmodel

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\...\venv\lib\site-packages\huey\api.py", line 367, in _execute
    task_value = task.execute()
  File "C:\Users\...\venv\lib\site-packages\huey\api.py", line 740, in execute
    return func(*args, **kwargs)
  File "C:\Users\...\venv\lib\site-packages\huey\contrib\djhuey\__init__.py", line 133, in inner
    return fn(*args, **kwargs)
  File "C:\Users\...\goodies\decorators\debug.py", line 74, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\...\puzzles\tasks\puzzles.py", line 49, in recalculate_pzl_medians
    unit='puzzles',
  File "C:\Users\...\venv\lib\site-packages\huey_monitor\tqdm.py", line 47, in __init__
    unit_divisor=self.unit_divisor,
  File "C:\Users\...\venv\lib\site-packages\django\db\models\query.py", line 783, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1535, in execute_sql
    cursor = super().execute_sql(result_type)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1169, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\...\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: huey_monitor_taskmodel

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\...\venv\lib\site-packages\huey\api.py", line 274, in _emit
    self._signal.send(signal, task, *args, **kwargs)
  File "C:\Users\...\venv\lib\site-packages\huey\signals.py", line 41, in send
    receiver(signal, task, *args, **kwargs)
  File "C:\Users\...\venv\lib\site-packages\huey_monitor\tasks.py", line 49, in store_signals
    defaults={'name': task.name}
  File "C:\Users\...\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "C:\Users\...\venv\lib\site-packages\nplusone\core\signals.py", line 23, in wrapped
    ret = func(*args, **kwargs)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\Users\...\venv\lib\site-packages\nplusone\ext\django\patch.py", line 295, in fetch_all
    original_fetch_all(self)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\...\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\...\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1169, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 78, in _execute
    self.db.validate_no_broken_transaction()
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\base\base.py", line 448, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
Traceback (most recent call last):
  File "C:\Users\...\venv\lib\site-packages\django\db\migrations\executor.py", line 229, in apply_migration
    self.record_migration(migration)
  File "C:\Users\...\venv\lib\site-packages\django\db\migrations\executor.py", line 244, in record_migration
    self.recorder.record_applied(migration.app_label, migration.name)
  File "C:\Users\...\venv\lib\site-packages\django\db\migrations\recorder.py", line 86, in record_applied
    self.ensure_schema()
  File "C:\Users\...\venv\lib\site-packages\django\db\migrations\recorder.py", line 63, in ensure_schema
    if self.has_table():
  File "C:\Users\...\venv\lib\site-packages\django\db\migrations\recorder.py", line 56, in has_table
    tables = self.connection.introspection.table_names(cursor)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\base\introspection.py", line 52, in table_names
    return get_names(cursor)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\base\introspection.py", line 47, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\sqlite3\introspection.py", line 77, in get_table_list
    ORDER BY name""")
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 78, in _execute
    self.db.validate_no_broken_transaction()
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\base\base.py", line 448, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    main()
  File "manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\...\venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\...\venv\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\...\venv\lib\site-packages\django\core\management\commands\test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "C:\Users\...\venv\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\...\venv\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\...\venv\lib\site-packages\django\core\management\commands\test.py", line 55, in handle
    failures = test_runner.run_tests(test_labels)
  File "C:\Users\...\venv\lib\site-packages\django\test\runner.py", line 725, in run_tests
    old_config = self.setup_databases(aliases=databases)
  File "C:\Users\...\venv\lib\site-packages\django\test\runner.py", line 645, in setup_databases
    debug_sql=self.debug_sql, parallel=self.parallel, **kwargs
  File "C:\Users\...\venv\lib\site-packages\django\test\utils.py", line 183, in setup_databases
    serialize=connection.settings_dict['TEST'].get('SERIALIZE', True),
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\base\creation.py", line 79, in create_test_db
    run_syncdb=True,
  File "C:\Users\...\venv\lib\site-packages\django\core\management\__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "C:\Users\...\venv\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\...\venv\lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\...\venv\lib\site-packages\django\core\management\commands\migrate.py", line 246, in handle
    fake_initial=fake_initial,
  File "C:\Users\...\venv\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\...\venv\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\...\venv\lib\site-packages\django\db\migrations\executor.py", line 230, in apply_migration
    migration_recorded = True
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\sqlite3\schema.py", line 35, in __exit__
    self.connection.check_constraints()
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in check_constraints
    violations = cursor.execute('PRAGMA foreign_key_check').fetchall()
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\utils.py", line 78, in _execute
    self.db.validate_no_broken_transaction()
  File "C:\Users\...\venv\lib\site-packages\django\db\backends\base\base.py", line 448, in validate_no_broken_transaction
    "An error occurred in the current transaction. You can't "
django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```

**Comment by jedie** [comment]
The real error is: `no such table: huey_monitor_taskmodel` So migrations are not done, yet.

Btw. you are under windows. I don't know if everything works under windows. Maybe we should expand our github CI pipeline and test under macos and windows, too.
On the other hand, no one will seriously run a django project on windows for production and it's always a good idea to develop in a environment that's "near" to productive.

I close this issues, because i thinks it's not related to our code, isn't it? Feel free to reopen/command here ;)

**Comment by Skrattoune** [comment]
I finally found the source of the error:
during the setting of the testing environnement, the migrations are run.

Among my migrations was one which was launching at some point a task.
And as the testing database did not contained at this point the huey-monitor tables yet (concerned migrations are far way down in the pipeline), it created the error.

Therefore, the issue is much more linked to the huey_monitor code than what we initially thought.
Now that it has been identified, This type of error could be catched and a more user-friendly error description could be implemented.
